<?php

/**
 * @file
 * Module file for Freshbook Module
 */




/**
 * Page call back for Freshdesk SSO
 */
function _freshdesk_support_portal() {
  global $user;
  header("Location: " . freshdesk_login_url($user->name, $user->email));
  return TRUE;
}

/**
 * Freshdesk SSO helper function to create login URL.
 */
function freshdesk_login_url($name, $email) {
  $secret = 'e063200f887bd522e86e809d6783db03';
  $base = 'https://swingsurgeon.freshdesk.com/';
  return $base . "login/sso/?name=" . urlencode($name) . "&email=" . urlencode($email) . "&hash=" . hash('md5', $name . $email . $secret);
}
