<?php

/**
 * @file
 * Module file for Freshbook Module
 */

/**
 * Implements hook_menu().
 */
function freshdesk_menu() {
  $items = array();
  $items['freshdesk/support/portal'] = array(
    'title' => 'Freshdesk Support Portal',
    'description' => 'Single Sign On to Support Portal',
    'page callback' => '_freshdesk_support_portal',
    'page arguments' => array(),
    'access callback' => 'user_is_logged_in',
    'type' => MENU_LOCAL_TASK,
  );
  return $items;
}

/**
 * Page call back for Freshdesk SSO
 */
function _freshdesk_support_portal() {
  global $user;
  header("Location: " . freshdesk_login_url($user->name, $user->email));
  return TRUE;
}

/**
 * Freshdesk SSO helper function to create login URL.
 */
function freshdesk_login_url($name, $email) {
  $secret = variable_get('freshdesk_sso_secret', '');
  $base = 'https://swingsurgeon.freshdesk.com/';
  return $base . "login/sso/?name=" . urlencode($name) . "&email=" . urlencode($email) . "&hash=" . hash('md5', $name . $email . $secret);
}
