<?php

/**
 * @file
 * Module file for Freshbook Module
 */

/**
 * Implements hook_menu().
 */
function freshdesk_menu() {
  $items = array();
  $items['admin/config/services/freshdesk'] = array(
    'title' => 'Freshdesk Admin Page',
    'description' => 'Freshdesk Adminstrative Settings',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('freshdesk_admin_account'),
    'access arguments' => array('administer freshdesk module'),
    'file' => 'freshdesk.admin.inc',
    'type' => MENU_NORMAL_ITEM,
  );
  $items['admin/config/services/freshdesk/default'] = array(
    'title' => 'Freshdesk Admin Page',
    'weight' => 0,
    'type' => MENU_DEFAULT_LOCAL_TASK,
  );
  $items['admin/config/services/freshdesk/widgetpopup'] = array(
    'title' => 'Freshdesk Popup Widget',
    'description' => 'Popup Widget Settings',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('freshdesk_admin_widget_popup'),
    'access arguments' => array('administer freshdesk module'),
    'file' => 'freshdesk.admin.inc',
    'type' => MENU_LOCAL_TASK,
    'weight' => 5,
  );
  $items['admin/config/services/freshdesk/widgetembed'] = array(
    'title' => 'Freshdesk Embed Widget',
    'description' => 'Embed Widget Settings',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('freshdesk_admin_widget_embed'),
    'access arguments' => array('administer freshdesk module'),
    'file' => 'freshdesk.admin.inc',
    'type' => MENU_LOCAL_TASK,
    'weight' => 6,
  );
  $items['freshdesk/support/portal'] = array(
    'title' => 'Freshdesk Support Portal',
    'description' => 'Single Sign On to Support Portal',
    'page callback' => '_freshdesk_support_portal',
    'page arguments' => array(),
    'access callback' => 'user_is_logged_in',
    'type' => MENU_LOCAL_TASK,
  );
  return $items;
}

/**
 * Implements hook_permission().
 */
function freshdesk_permission() {
  return array(
    'administer freshdesk module' => array(
      'title' => t('Administer Freshdesk Module'),
    ),
  );
}

/**
 * Page call back for Freshdesk SSO
 */
function _freshdesk_support_portal() {
  global $user;
  header("Location: " . freshdesk_login_url($user->name, $user->email));
  return TRUE;
}

/**
 * Freshdesk SSO helper function to create login URL.
 */
function freshdesk_login_url($name, $email) {
  $secret = variable_get('freshdesk_sso_key', '');
  $base = variable_get('freshdesk_url', '');
  return $base . '/login/sso/?name=' . urlencode($name) . '&email=' . urlencode($email) . '&hash=' . hash('md5', $name . $email . $secret);
}
